# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore UnitTestProject

    - name: Build
      run: dotnet build UnitTestProject --no-restore

    - name: Run Tests and Generate .trx Result
      run: |
        mkdir -p TestResults
        dotnet test ./UnitTestProject.Test/UnitTestProject.Test.csproj \
          --filter "Category!=Integration" \
          --logger "trx;LogFileName=test_results.trx" \
          --results-directory TestResults

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: TestResults/*.trx



